version: '3.8'
services:
  web:
    build: .
    command: python -m flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=partyqueue.app
      - FLASK_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/partyqueue
      - SECRET_KEY=changeme
      - YOUTUBE_API_KEY=your_youtube_key_here
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
